-- Branding Logo table for storing custom logo images (light/dark)
CREATE TABLE branding_logo (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mandat      VARCHAR(100)  NOT NULL,
    theme       VARCHAR(10)   NOT NULL, -- 'light' or 'dark'
    image_data  TEXT          NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_name   VARCHAR(255),
    logo_width  INTEGER       DEFAULT 180,
    logo_height INTEGER       DEFAULT 40,
    created_date     TIMESTAMP NOT NULL,
    created_by       VARCHAR(255),
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255),
    CONSTRAINT uq_branding_logo_mandat_theme UNIQUE (mandat, theme)
);
