-- Create Anforderung table
CREATE TABLE IF NOT EXISTS ANFORDERUNG (
  ID BIGSERIAL,
  BESCHREIBUNG VARCHAR(5000),
  CREATED_BY VARCHAR(255),
  CREATED_DATE TIMESTAMP NOT NULL,
  ERLEDIGT_DATUM TIMESTAMP,
  ERSTELLER VARCHAR(255),
  FAELLIGKEIT_DATUM TIMESTAMP,
  KATEGORIE VARCHAR(100),
  LAST_MODIFIED_BY VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP,
  MANDAT VARCHAR(100) NOT NULL,
  PRIORITY VARCHAR(50),
  STATUS VARCHAR(50),
  TITEL VARCHAR(500) NOT NULL,
  ZUGEWIESEN_AN VARCHAR(255),
  PRIMARY KEY (ID)
);
