-- Create Cron tables
CREATE TABLE IF NOT EXISTS CRON_CONFIG (
  ID BIGSERIAL,
  CREATED_BY VARCHAR(255),
  CREATED_DATE TIMESTAMP,
  CRON_EXPRESSION VARCHAR(255),
  CRON_NAME VARCHAR(255) NOT NULL,
  ENABLED BOOLEAN NOT NULL,
  LAST_MODIFIED_BY VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP,
  MANDAT VARCHAR(255) NOT NULL,
  STARTUP BOOLEAN NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CRON_STATE (
  ID BIGSERIAL,
  CREATED_BY VARCHAR(255),
  CREATED_DATE TIMESTAMP,
  DELETED BOOLEAN,
  LAST_MODIFIED_BY VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP,
  MANDAT VARCHAR(255),
  TAGS VARCHAR(5000),
  CRON_EXPRESSION VARCHAR(255),
  ENABLED BOOLEAN NOT NULL,
  GLOBAL BOOLEAN NOT NULL,
  JOB_NAME VARCHAR(255),
  STARTUP BOOLEAN NOT NULL,
  PRIMARY KEY (ID)
);
