-- Create Howto table for reusable instructions
CREATE TABLE howto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    instructions TEXT NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    created_date TIMESTAMP,
    last_modified_date TIMESTAMP
);

-- Add howto_ids column to anforderung table
-- This stores comma-separated Howto IDs for selected howtos
ALTER TABLE anforderung ADD COLUMN howto_ids VARCHAR(1000);
