-- Create Werteliste tables
CREATE TABLE IF NOT EXISTS WERTELISTE (
  WERTE_KEY VARCHAR(255) NOT NULL,
  MANDAT VARCHAR(100) NOT NULL,
  CREATED_BY VARCHAR(255),
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP,
  PRIMARY KEY (MANDAT, WERTE_KEY)
);

CREATE TABLE IF NOT EXISTS WERTELISTE_ENTRY (
  ID BIGSERIAL,
  SORT_ORDER INTEGER NOT NULL,
  ENTRY_VALUE VARCHAR(500) NOT NULL,
  WERTELISTE_KEY VARCHAR(255),
  WERTELISTE_MANDAT VARCHAR(100),
  PRIMARY KEY (ID)
);
