-- Create Setting table
CREATE TABLE IF NOT EXISTS SETTING (
  SETTING_KEY VARCHAR(500) NOT NULL,
  MANDAT VARCHAR(100) NOT NULL,
  CREATED_BY VARCHAR(255),
  CREATED_DATE TIMESTAMP NOT NULL,
  DESCRIPTION VARCHAR(1000),
  LAST_MODIFIED_BY VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP,
  SETTING_VALUE VARCHAR(5000),
  VALUE_TYPE VARCHAR(50),
  PRIMARY KEY (MANDAT, SETTING_KEY)
);
