-- Create User Session table
CREATE TABLE IF NOT EXISTS USER_SESSION (
  ID BIGSERIAL,
  ACTIVE BOOLEAN NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_ACTIVITY_TIME TIMESTAMP NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP,
  LOGIN_TIME TIMESTAMP NOT NULL,
  MANDAT VARCHAR(100) NOT NULL,
  SESSION_ID VARCHAR(255) NOT NULL,
  USER_AGENT VARCHAR(1000),
  USER_ID BIGINT NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT uk_user_session_session_id UNIQUE (SESSION_ID)
);
