-- Create Rollenzuteilung table
CREATE TABLE IF NOT EXISTS ROLLENZUTEILUNG (
  ID BIGSERIAL,
  ACTIVE BOOLEAN NOT NULL,
  BESCHREIBUNG VARCHAR(1000),
  CREATED_BY VARCHAR(255),
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP,
  MANDAT VARCHAR(100) NOT NULL,
  ROLE_NAME VARCHAR(100) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  VALID_FROM TIMESTAMP,
  VALID_UNTIL TIMESTAMP,
  PRIMARY KEY (ID)
);
