-- Create File Metadata table
CREATE TABLE IF NOT EXISTS FILE_METADATA (
  ID BIGSERIAL,
  ACCESS_COUNT INTEGER,
  BESCHREIBUNG VARCHAR(2000),
  CATEGORY VARCHAR(100),
  CHECKSUM VARCHAR(64),
  CONTENT_TYPE VARCHAR(255),
  CREATED_BY VARCHAR(255),
  CREATED_DATE TIMESTAMP NOT NULL,
  FILE_PATH VARCHAR(2000) NOT NULL,
  FILE_SIZE BIGINT,
  FILENAME VARCHAR(500) NOT NULL,
  LAST_ACCESSED TIMESTAMP,
  LAST_MODIFIED_BY VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP,
  MANDAT VARCHAR(100) NOT NULL,
  ORIGINAL_FILENAME VARCHAR(500),
  STORAGE_BACKEND VARCHAR(50) NOT NULL,
  TAGS VARCHAR(1000),
  UPLOADED_BY VARCHAR(255),
  PRIMARY KEY (ID)
);
