-- Create new table for global API settings
CREATE TABLE anforderung_api_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_token VARCHAR(500),
    claude_automation_enabled BOOLEAN,
    menu_name VARCHAR(100) DEFAULT 'Anforderungen Einstellungen, API'
);

-- Insert default settings (copy from first anforderung if exists)
INSERT INTO anforderung_api_settings (api_token, claude_automation_enabled, menu_name)
SELECT
    COALESCE(a.api_token, NULL),
    COALESCE(a.claude_automation_enabled, FALSE),
    'Anforderungen Einstellungen, API'
FROM anforderung a
WHERE a.id = (SELECT MIN(id) FROM anforderung);

-- If no anforderung data exists, insert default values
INSERT INTO anforderung_api_settings (api_token, claude_automation_enabled, menu_name)
SELECT * FROM (VALUES (NULL, FALSE, 'Anforderungen Einstellungen, API'))
WHERE NOT EXISTS (SELECT 1 FROM anforderung_api_settings);

-- Remove columns from anforderung table (only if they exist)
-- HSQLDB doesn't support IF EXISTS in DROP COLUMN, so we use a workaround
-- First check if columns exist, then drop them
ALTER TABLE anforderung DROP COLUMN api_token;
ALTER TABLE anforderung DROP COLUMN claude_automation_enabled;
ALTER TABLE anforderung DROP COLUMN is_default;
