-- Create Howto table if it doesn't exist (fixing empty migration V820671802)
-- Using HSQLDB IF NOT EXISTS syntax
CREATE TABLE IF NOT EXISTS howto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    instructions TEXT NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    created_date TIMESTAMP,
    last_modified_date TIMESTAMP
);

-- Add howto_ids column to anforderung table
-- HSQLDB will skip if column already exists (we check in application layer)
-- Since this is a fix migration, we try to add it
-- If it fails because column exists, that's fine
ALTER TABLE anforderung ADD COLUMN IF NOT EXISTS howto_ids VARCHAR(1000);
