-- Create Webapp tables (Legacy, Common, Security)
CREATE TABLE IF NOT EXISTS DBAUTH_USER (
  ID BIGSERIAL,
  CREATED_BY VARCHAR(255),
  CREATED_DATE TIMESTAMP,
  DELETED BOOLEAN,
  LAST_MODIFIED_BY VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP,
  MANDAT VARCHAR(255),
  TAGS VARCHAR(5000),
  ANREDE VARCHAR(255),
  AUTHORITIES_STRING TEXT,
  AUTOLOGIN BOOLEAN NOT NULL,
  GEBURTSTAG TIMESTAMP,
  GESPERRT BOOLEAN NOT NULL,
  KEY_CLOAK BOOLEAN,
  LAST_SEEN TIMESTAMP,
  LINKTOKEN VARCHAR(255),
  LOGINCOUNT INTEGER,
  MAIL VARCHAR(255),
  MANDANT VARCHAR(255),
  MOBILE VARCHAR(255),
  NACHNAME VARCHAR(255),
  ORIG_CLASS VARCHAR(255),
  ORIG_ID BIGINT,
  ORT VARCHAR(255),
  PLZ VARCHAR(255),
  STRASSE_UND_NUMMER VARCHAR(255),
  USERGUUID VARCHAR(255),
  USERNAME VARCHAR(255),
  VORNAME VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS DBAUTH_PROPERTIES (
  DBAUTH_USER_ID BIGINT NOT NULL,
  PROPERTIES VARCHAR(255),
  PROPERTIES_KEY VARCHAR(255) NOT NULL,
  PRIMARY KEY (DBAUTH_USER_ID, PROPERTIES_KEY)
);

CREATE TABLE IF NOT EXISTS TEXT2 (
  ID BIGSERIAL,
  CREATED_BY VARCHAR(255),
  CREATED_DATE TIMESTAMP,
  DELETED BOOLEAN,
  LAST_MODIFIED_BY VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP,
  MANDAT VARCHAR(255),
  TAGS VARCHAR(5000),
  INDEX VARCHAR(255),
  INDEX1 VARCHAR(255),
  INDEX2 VARCHAR(255),
  INDEX3 VARCHAR(255),
  INDEX4 VARCHAR(255),
  KEY VARCHAR(255),
  TYPE VARCHAR(255),
  VALUE VARCHAR(200000),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MY_USER_ENTITY (
  ID BIGSERIAL,
  AUTOLOGIN_KEY VARCHAR(255),
  PASSWORD VARCHAR(255),
  ROLES VARCHAR(255),
  STARTPAGE VARCHAR(255),
  USERNAME VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PERSISTENT_LOGINS (
  SERIES VARCHAR(255) NOT NULL,
  LAST_USED TIMESTAMP,
  TOKEN VARCHAR(255),
  USERNAME VARCHAR(255),
  PRIMARY KEY (SERIES)
);

CREATE TABLE IF NOT EXISTS SIMPLE_STORABLE_ENTITY (
  ID BIGSERIAL,
  MY_OBJECT VARCHAR(30000),
  UNIQUE_ID VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);
