-- Create Menuesteuerung tables
CREATE TABLE IF NOT EXISTS MANDATE_MENU_CONFIG (
  ID BIGSERIAL,
  MANDATE_NAME VARCHAR(255) NOT NULL,
  IS_WHITELIST_MODE BOOLEAN,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MANDATE_HIDDEN_MENUS (
  CONFIG_ID BIGINT NOT NULL,
  MENU_TITLE VARCHAR(255)
);
