-- MQTT Konfigurationsfelder in GameModel
ALTER TABLE game_model ADD COLUMN mqtt_broker_url VARCHAR(255) DEFAULT 'tcp://192.168.1.224';
ALTER TABLE game_model ADD COLUMN mqtt_port INTEGER DEFAULT 1883;
ALTER TABLE game_model ADD COLUMN mqtt_topic VARCHAR(255) DEFAULT 'schuetu/events';
ALTER TABLE game_model ADD COLUMN mqtt_mode VARCHAR(10) DEFAULT 'OUT';
ALTER TABLE game_model ADD COLUMN mqtt_enabled BOOLEAN DEFAULT FALSE;

-- Tabelle fuer konsumierte MQTT-Nachrichten
CREATE TABLE mqtt_consumed_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash VARCHAR(255) NOT NULL UNIQUE,
    event_type VARCHAR(255) NOT NULL,
    payload CLOB,
    received_at TIMESTAMP NOT NULL,
    processed BOOLEAN DEFAULT FALSE,
    game VARCHAR(255)
);
