#!/bin/bash
# ═══════════════════════════════════════════════════════════════
#  HSQLDB → PostgreSQL Data Migration Script
#
#  Migrates data from old schuetu HSQLDB (NAS Docker volume)
#  to the new PostgreSQL database.
#
#  Prerequisites:
#  - NAS reachable (stop Twingate if needed)
#  - PostgreSQL running (docker compose up)
#  - HSQLDB files accessible on NAS
#
#  Old HSQLDB path on NAS Docker: /data/schuetu/schuetu
#  (mounted from NAS volume, likely under /volume1/docker/...)
# ═══════════════════════════════════════════════════════════════

set -e

NAS_HOST="192.168.1.224"
NAS_USER="mad"

# Where the old HSQLDB data lives (search these paths)
HSQLDB_SEARCH_PATHS=(
    "/volume1/docker/schuetu"
    "/volume1/docker/project-schuetu-prod"
    "/volume1/docker/emad-schuetu"
    "/data/schuetu"
    "/data/project-schuetu-prod"
)

LOCAL_PG_HOST="localhost"
LOCAL_PG_PORT="5434"
LOCAL_PG_DB="plaintext_schuetu"
LOCAL_PG_USER="plaintext"

echo "=== HSQLDB → PostgreSQL Migration für Schülerturnier ==="
echo ""

# Step 1: Find HSQLDB files on NAS
echo "1. Suche HSQLDB-Dateien auf NAS..."
for path in "${HSQLDB_SEARCH_PATHS[@]}"; do
    echo "   Prüfe: $path"
    FILES=$(ssh -o ConnectTimeout=5 "${NAS_USER}@${NAS_HOST}" \
        "find '$path' -name '*.script' -o -name '*.data' -o -name '*.properties' 2>/dev/null" 2>/dev/null || true)
    if [ -n "$FILES" ]; then
        echo "   GEFUNDEN:"
        echo "$FILES" | sed 's/^/     /'
        HSQLDB_DIR="$path"
        break
    fi
done

if [ -z "$HSQLDB_DIR" ]; then
    echo "   HSQLDB-Dateien nicht gefunden auf NAS."
    echo "   Bitte manuell suchen: ssh ${NAS_USER}@${NAS_HOST} 'find / -name schuetu.script 2>/dev/null'"
    exit 1
fi

# Step 2: Copy HSQLDB files locally
echo ""
echo "2. Kopiere HSQLDB-Dateien lokal..."
WORK_DIR="/tmp/schuetu-migration"
mkdir -p "$WORK_DIR"
scp "${NAS_USER}@${NAS_HOST}:${HSQLDB_DIR}/schuetu.*" "$WORK_DIR/" 2>/dev/null || \
scp "${NAS_USER}@${NAS_HOST}:${HSQLDB_DIR}/schuetu/schuetu.*" "$WORK_DIR/"
echo "   Dateien kopiert nach: $WORK_DIR"
ls -la "$WORK_DIR"

# Step 3: Extract INSERT statements from HSQLDB .script file
echo ""
echo "3. Extrahiere INSERT-Statements aus HSQLDB..."
SCRIPT_FILE="$WORK_DIR/schuetu.script"
if [ ! -f "$SCRIPT_FILE" ]; then
    echo "   FEHLER: $SCRIPT_FILE nicht gefunden"
    exit 1
fi

# Extract INSERT statements and convert HSQLDB syntax to PostgreSQL
OUTPUT_FILE="$WORK_DIR/postgres-import.sql"

cat > "$OUTPUT_FILE" << 'SQLHEADER'
-- Auto-generated PostgreSQL import from HSQLDB
-- Generated by migrate-hsqldb-to-postgres.sh
BEGIN;

-- Disable triggers during import
SET session_replication_role = replica;

SQLHEADER

# Extract and convert INSERT statements
grep "^INSERT INTO" "$SCRIPT_FILE" | \
    sed 's/PUBLIC\.//g' | \
    sed "s/TRUE/true/g" | \
    sed "s/FALSE/false/g" | \
    sed 's/SPIELZEILE/spiel_zeile/g' | \
    sed 's/GAMEMODEL/game_model/g' | \
    sed 's/TEXT2/text2/g' >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'SQLFOOTER'

-- Re-enable triggers
SET session_replication_role = DEFAULT;

-- Reset sequences to max(id) + 1
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE format('SELECT setval(pg_get_serial_sequence(''%I'', ''id''), COALESCE(MAX(id), 0) + 1, false) FROM %I', r.tablename, r.tablename);
    END LOOP;
END $$;

COMMIT;
SQLFOOTER

echo "   SQL-Import-Datei erstellt: $OUTPUT_FILE"
INSERTS=$(grep -c "^INSERT" "$OUTPUT_FILE" || echo "0")
echo "   Anzahl INSERT-Statements: $INSERTS"

# Step 4: Import into PostgreSQL
echo ""
echo "4. Import nach PostgreSQL..."
echo "   Ziel: $LOCAL_PG_HOST:$LOCAL_PG_PORT/$LOCAL_PG_DB"
read -p "   Fortfahren? (j/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Jj]$ ]]; then
    PGPASSWORD=plaintext psql -h "$LOCAL_PG_HOST" -p "$LOCAL_PG_PORT" -U "$LOCAL_PG_USER" -d "$LOCAL_PG_DB" -f "$OUTPUT_FILE"
    echo "   Import abgeschlossen!"
else
    echo "   Import abgebrochen. SQL-Datei verfügbar unter: $OUTPUT_FILE"
fi

echo ""
echo "=== Migration abgeschlossen ==="
